# Generated by Django 4.0 on 2022-05-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
